DROP TABLE IF EXISTS SPRZATANIE_CZYNNOSCI;
DROP TABLE IF EXISTS UROCZYSTOSCI;
DROP TABLE IF EXISTS JEDZENIE_PRZEPISY;
DROP TABLE IF EXISTS KONFIGURACJA_DOM;

CREATE TABLE SPRZATANIE_CZYNNOSCI(
  NAZWA VARCHAR(180) PRIMARY KEY NOT NULL COLLATE utf8_polish_ci,
  DATA_OSTATNIEGO_SPRZATANIA DATE,
  DATA_NASTEPNEGO_SPRZATANIA DATE,
  CZESTOTLIWOSC INT(6) NOT NULL
);

CREATE TABLE UROCZYSTOSCI(
  OSOBA VARCHAR(180) NOT NULL COLLATE utf8_polish_ci,
  DATA_UROCZYSTOSCI DATE NOT NULL,
  RODZAJ VARCHAR(50) NOT NULL COLLATE utf8_polish_ci
);

CREATE TABLE JEDZENIE_PRZEPISY(
  NAZWA VARCHAR(180) PRIMARY KEY NOT NULL,
  DATA_OSTATNIEGO_PRZYGOTOWANIA DATE,
  SKLADNIKI VARCHAR(500),
  SPOSOB_PRZYGOTOWANIA VARCHAR(500)
)COLLATE='utf8_polish_ci';

CREATE TABLE KONFIGURACJA_DOM(
    NAZWA_SCIEZKI VARCHAR(255),
    SCIEZKA VARCHAR(255)
)COLLATE='utf8_polish_ci';