DROP TABLE IF EXISTS SPRZATANIE_CZYNNOSC;

CREATE TABLE SPRZATANIE_CZYNNOSC(
  NAZWA VARCHAR(180) PRIMARY KEY NOT NULL COLLATE utf8_polish_ci,
  DATA_OSTATNIEGO_SPRZATANIA DATE,
  DATA_NASTEPNEGO_SPRZATANIA DATE,
  CZESTOTLIWOSC INT(6) NOT NULL
);